-- Adds single-choice chat polls for CourseGuard.
-- Safe to run multiple times on PostgreSQL / Supabase.

CREATE TABLE IF NOT EXISTS POLLS (
    ID SERIAL PRIMARY KEY,
    COURSE_ID INT NOT NULL,
    MESSAGE_ID INT NOT NULL UNIQUE,
    CREATED_BY INT NOT NULL,
    QUESTION TEXT NOT NULL,
    IS_CLOSED BOOLEAN NOT NULL DEFAULT FALSE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CLOSED_AT TIMESTAMP,

    CONSTRAINT FK_POLLS_COURSES
        FOREIGN KEY (COURSE_ID) REFERENCES COURSES(ID) ON DELETE CASCADE,
    CONSTRAINT FK_POLLS_MESSAGES
        FOREIGN KEY (MESSAGE_ID) REFERENCES MESSAGES(ID) ON DELETE CASCADE,
    CONSTRAINT FK_POLLS_USERS
        FOREIGN KEY (CREATED_BY) REFERENCES USERS(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS POLL_OPTIONS (
    ID SERIAL PRIMARY KEY,
    POLL_ID INT NOT NULL,
    OPTION_TEXT TEXT NOT NULL,
    SORT_ORDER INT NOT NULL DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_POLL_OPTIONS_POLLS
        FOREIGN KEY (POLL_ID) REFERENCES POLLS(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS POLL_VOTES (
    POLL_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    OPTION_ID INT NOT NULL,
    VOTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT PK_POLL_VOTES PRIMARY KEY (POLL_ID, USER_ID),
    CONSTRAINT FK_POLL_VOTES_POLLS
        FOREIGN KEY (POLL_ID) REFERENCES POLLS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_POLL_VOTES_USERS
        FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_POLL_VOTES_OPTIONS
        FOREIGN KEY (OPTION_ID) REFERENCES POLL_OPTIONS(ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_POLLS_COURSE_ID ON POLLS(COURSE_ID);
CREATE INDEX IF NOT EXISTS IDX_POLLS_MESSAGE_ID ON POLLS(MESSAGE_ID);
CREATE INDEX IF NOT EXISTS IDX_POLL_OPTIONS_POLL_ID ON POLL_OPTIONS(POLL_ID);
CREATE INDEX IF NOT EXISTS IDX_POLL_OPTIONS_SORT_ORDER ON POLL_OPTIONS(POLL_ID, SORT_ORDER, ID);
CREATE INDEX IF NOT EXISTS IDX_POLL_VOTES_POLL_ID ON POLL_VOTES(POLL_ID);
CREATE INDEX IF NOT EXISTS IDX_POLL_VOTES_OPTION_ID ON POLL_VOTES(OPTION_ID);

-- Guardrail: every vote option must belong to the same poll being voted on.
CREATE OR REPLACE FUNCTION COURSEGUARD_VALIDATE_POLL_VOTE_OPTION()
RETURNS TRIGGER AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM POLL_OPTIONS po
        WHERE po.ID = NEW.OPTION_ID
          AND po.POLL_ID = NEW.POLL_ID
    ) THEN
        RAISE EXCEPTION 'POLL_VOTES.OPTION_ID must belong to POLL_VOTES.POLL_ID';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS TRG_VALIDATE_POLL_VOTE_OPTION ON POLL_VOTES;
CREATE TRIGGER TRG_VALIDATE_POLL_VOTE_OPTION
BEFORE INSERT OR UPDATE ON POLL_VOTES
FOR EACH ROW
EXECUTE FUNCTION COURSEGUARD_VALIDATE_POLL_VOTE_OPTION();
