CREATE TABLE IF NOT EXISTS LOGIN_DAILY_STATS (
    STAT_DATE DATE PRIMARY KEY,
    LOGIN_COUNT INT NOT NULL DEFAULT 0,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS IDX_LOGIN_DAILY_STATS_DATE
    ON LOGIN_DAILY_STATS (STAT_DATE DESC);
