-- Extend COURSES table to store academic timetable metadata.
-- Safe to run multiple times.

ALTER TABLE COURSES ADD COLUMN IF NOT EXISTS COURSE_CODE VARCHAR(20);
ALTER TABLE COURSES ADD COLUMN IF NOT EXISTS CLASS_CODE VARCHAR(50);
ALTER TABLE COURSES ADD COLUMN IF NOT EXISTS CREDITS INT;
ALTER TABLE COURSES ADD COLUMN IF NOT EXISTS INSTRUCTOR_TEXT VARCHAR(255);
ALTER TABLE COURSES ADD COLUMN IF NOT EXISTS SCHEDULE_TEXT VARCHAR(255);

CREATE INDEX IF NOT EXISTS IDX_COURSES_CODE ON COURSES (COURSE_CODE);
CREATE INDEX IF NOT EXISTS IDX_COURSES_CLASS_CODE ON COURSES (CLASS_CODE);
