-- NT106 CONSOLIDATED SCHEMA
-- Gộp toàn bộ file SQL hiện có thành một file duy nhất.
-- Nguồn gộp:
-- 1) SupabaseSchema.sql
-- 2) Migrations/20260415_security_constraints.sql
-- 3) Migrations/20260415_extend_courses_for_schedule.sql
-- 4) Migrations/20260416_normalize_user_status.sql

-- =========================================================
-- [BEGIN] SupabaseSchema.sql
-- =========================================================
-- SUPABASE (POSTGRESQL) SCHEMA INIT SCRIPT
-- Bỏ qua lệnh CREATE DATABASE / USE vì Supabase đã tự xử lý Database mặc định là postgres.

-- RESET ALL TABLES (RUN BEFORE RE-CREATE SCHEMA)
-- Lưu ý: Lệnh này sẽ XÓA TOÀN BỘ DỮ LIỆU.
DROP TABLE IF EXISTS ROLE_PERMISSIONS CASCADE;
DROP TABLE IF EXISTS PERMISSIONS CASCADE;
DROP TABLE IF EXISTS MESSAGES CASCADE;
DROP TABLE IF EXISTS MATERIALS CASCADE;
DROP TABLE IF EXISTS ONLINE_SESSIONS CASCADE;
DROP TABLE IF EXISTS ANSWERS CASCADE;
DROP TABLE IF EXISTS EXAM_QUESTIONS CASCADE;
DROP TABLE IF EXISTS VIOLATIONS CASCADE;
DROP TABLE IF EXISTS EXAM_ATTEMPTS CASCADE;
DROP TABLE IF EXISTS QUESTIONS CASCADE;
DROP TABLE IF EXISTS EXAMS CASCADE;
DROP TABLE IF EXISTS ENROLLMENTS CASCADE;
DROP TABLE IF EXISTS COURSES CASCADE;
DROP TABLE IF EXISTS NOTIFICATIONS CASCADE;
DROP TABLE IF EXISTS DEVICES CASCADE;
DROP TABLE IF EXISTS AUDIT_LOGS CASCADE;
DROP TABLE IF EXISTS USERS CASCADE;
DROP TABLE IF EXISTS ROLES CASCADE;

-- ROLES
CREATE TABLE ROLES (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR(255)
);

-- USERS
CREATE TABLE USERS (
    ID SERIAL PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    FULL_NAME VARCHAR(100),
    EMAIL VARCHAR(100) UNIQUE,
    ROLE_ID INT NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_USERS_ROLES
    FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID)
);

-- PERMISSIONS
CREATE TABLE PERMISSIONS (
    ID SERIAL PRIMARY KEY,
    CODE VARCHAR(100) NOT NULL UNIQUE,
    NAME VARCHAR(100),
    DESCRIPTION VARCHAR(255),
    IS_ACTIVE BOOLEAN DEFAULT TRUE
);

-- ROLE_PERMISSIONS
CREATE TABLE ROLE_PERMISSIONS (
    ROLE_ID INT NOT NULL,
    PERMISSION_ID INT NOT NULL,

    PRIMARY KEY (ROLE_ID, PERMISSION_ID),

    FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID) ON DELETE CASCADE,
    FOREIGN KEY (PERMISSION_ID) REFERENCES PERMISSIONS(ID) ON DELETE CASCADE
);

-- COURSES
CREATE TABLE COURSES (
    ID SERIAL PRIMARY KEY,
    COURSE_CODE VARCHAR(20),
    CLASS_CODE VARCHAR(50),
    NAME VARCHAR(200) NOT NULL,
    CREDITS INT,
    DESCRIPTION TEXT,
    TEACHER_ID INT NOT NULL,
    INSTRUCTOR_TEXT VARCHAR(255),
    SCHEDULE_TEXT VARCHAR(255),
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    START_DATE DATE,
    END_DATE DATE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (TEACHER_ID) REFERENCES USERS(ID)
);

-- ENROLLMENTS
CREATE TABLE ENROLLMENTS (
    ID SERIAL PRIMARY KEY,
    COURSE_ID INT NOT NULL,
    STUDENT_ID INT NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'PENDING',
    JOINED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (COURSE_ID) REFERENCES COURSES(ID) ON DELETE CASCADE,
    FOREIGN KEY (STUDENT_ID) REFERENCES USERS(ID)
);

-- EXAMS
CREATE TABLE EXAMS (
    ID SERIAL PRIMARY KEY,
    COURSE_ID INT NOT NULL,
    TITLE VARCHAR(200),
    OPEN_TIME TIMESTAMP,
    CLOSE_TIME TIMESTAMP,
    DURATION_MINUTES INT,
    MAX_ATTEMPTS INT DEFAULT 1,
    ALLOW_REVIEW BOOLEAN DEFAULT FALSE,
    SHUFFLE_QUESTIONS BOOLEAN DEFAULT FALSE,
    CREATED_BY INT,

    FOREIGN KEY (COURSE_ID) REFERENCES COURSES(ID) ON DELETE CASCADE,
    FOREIGN KEY (CREATED_BY) REFERENCES USERS(ID)
);

-- QUESTIONS
CREATE TABLE QUESTIONS (
    ID SERIAL PRIMARY KEY,
    COURSE_ID INT NOT NULL,
    CONTENT TEXT,
    TYPE VARCHAR(20),
    CORRECT_ANSWER TEXT,
    SCORE DECIMAL(5,2) DEFAULT 1,

    FOREIGN KEY (COURSE_ID) REFERENCES COURSES(ID) ON DELETE CASCADE
);

-- EXAM_QUESTIONS
CREATE TABLE EXAM_QUESTIONS (
    EXAM_ID INT NOT NULL,
    QUESTION_ID INT NOT NULL,

    PRIMARY KEY (EXAM_ID, QUESTION_ID),

    FOREIGN KEY (EXAM_ID) REFERENCES EXAMS(ID) ON DELETE CASCADE,
    FOREIGN KEY (QUESTION_ID) REFERENCES QUESTIONS(ID)
);

-- EXAM_ATTEMPTS
CREATE TABLE EXAM_ATTEMPTS (
    ID SERIAL PRIMARY KEY,
    EXAM_ID INT NOT NULL,
    STUDENT_ID INT NOT NULL,
    START_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    SUBMIT_TIME TIMESTAMP,
    SCORE DECIMAL(5,2),
    STATUS VARCHAR(20) DEFAULT 'IN_PROGRESS',

    FOREIGN KEY (EXAM_ID) REFERENCES EXAMS(ID) ON DELETE CASCADE,
    FOREIGN KEY (STUDENT_ID) REFERENCES USERS(ID)
);

-- ANSWERS
CREATE TABLE ANSWERS (
    ID SERIAL PRIMARY KEY,
    ATTEMPT_ID INT NOT NULL,
    QUESTION_ID INT NOT NULL,
    ANSWER_CONTENT TEXT,
    SCORE DECIMAL(5,2),

    FOREIGN KEY (ATTEMPT_ID) REFERENCES EXAM_ATTEMPTS(ID) ON DELETE CASCADE,
    FOREIGN KEY (QUESTION_ID) REFERENCES QUESTIONS(ID)
);

-- ONLINE_SESSIONS
CREATE TABLE ONLINE_SESSIONS (
    ID SERIAL PRIMARY KEY,
    COURSE_ID INT NOT NULL,
    TITLE VARCHAR(200),
    START_TIME TIMESTAMP,
    END_TIME TIMESTAMP,
    MEETING_LINK VARCHAR(500),
    CREATED_BY INT,

    FOREIGN KEY (COURSE_ID) REFERENCES COURSES(ID) ON DELETE CASCADE,
    FOREIGN KEY (CREATED_BY) REFERENCES USERS(ID)
);

-- MATERIALS
CREATE TABLE MATERIALS (
    ID SERIAL PRIMARY KEY,
    COURSE_ID INT NOT NULL,
    FILE_NAME VARCHAR(255),
    FILE_PATH VARCHAR(500),
    UPLOADED_BY INT,
    UPLOADED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (COURSE_ID) REFERENCES COURSES(ID) ON DELETE CASCADE,
    FOREIGN KEY (UPLOADED_BY) REFERENCES USERS(ID)
);

-- MESSAGES
CREATE TABLE MESSAGES (
    ID SERIAL PRIMARY KEY,
    COURSE_ID INT NOT NULL,
    SENDER_ID INT NOT NULL,
    CONTENT TEXT,
    MESSAGE_TYPE VARCHAR(20) NOT NULL DEFAULT 'TEXT',
    FILE_URL TEXT,
    FILE_NAME VARCHAR(255),
    FILE_SIZE BIGINT,
    MIME_TYPE VARCHAR(100),
    REPLY_TO_ID INT,
    IS_DELETED BOOLEAN DEFAULT FALSE,
    SENT_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (COURSE_ID) REFERENCES COURSES(ID) ON DELETE CASCADE,
    FOREIGN KEY (SENDER_ID) REFERENCES USERS(ID),
    FOREIGN KEY (REPLY_TO_ID) REFERENCES MESSAGES(ID) ON DELETE SET NULL
);

-- CHAT_READS
CREATE TABLE CHAT_READS (
    USER_ID INT NOT NULL,
    COURSE_ID INT NOT NULL,
    LAST_READ_MESSAGE_ID INT,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (USER_ID, COURSE_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    FOREIGN KEY (COURSE_ID) REFERENCES COURSES(ID) ON DELETE CASCADE,
    FOREIGN KEY (LAST_READ_MESSAGE_ID) REFERENCES MESSAGES(ID) ON DELETE SET NULL
);

-- NOTIFICATIONS
CREATE TABLE NOTIFICATIONS (
    ID SERIAL PRIMARY KEY,
    USER_ID INT NOT NULL,
    TITLE VARCHAR(200),
    CONTENT TEXT,
    IS_READ BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

-- DEVICES
CREATE TABLE DEVICES (
    ID SERIAL PRIMARY KEY,
    USER_ID INT NOT NULL,
    DEVICE_NAME VARCHAR(200),
    IP_ADDRESS VARCHAR(50),
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    LAST_ACTIVE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

-- VIOLATIONS
CREATE TABLE VIOLATIONS (
    ID SERIAL PRIMARY KEY,
    USER_ID INT NOT NULL,
    EXAM_ATTEMPT_ID INT,
    TYPE VARCHAR(100),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    FOREIGN KEY (EXAM_ATTEMPT_ID) REFERENCES EXAM_ATTEMPTS(ID)
);

-- AUDIT_LOGS
CREATE TABLE AUDIT_LOGS (
    ID SERIAL PRIMARY KEY,
    USER_ID INT,
    ACTION VARCHAR(200),
    TARGET_TABLE VARCHAR(100),
    TARGET_ID INT,
    DETAILS TEXT,
    IP_ADDRESS VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

-- PERFORMANCE INDEXES (auth/activity monitoring)
CREATE INDEX IF NOT EXISTS IDX_USERS_STATUS ON USERS (STATUS);
CREATE INDEX IF NOT EXISTS IDX_COURSES_STATUS ON COURSES (STATUS);
CREATE INDEX IF NOT EXISTS IDX_COURSES_CODE ON COURSES (COURSE_CODE);
CREATE INDEX IF NOT EXISTS IDX_COURSES_CLASS_CODE ON COURSES (CLASS_CODE);
CREATE INDEX IF NOT EXISTS IDX_AUDIT_LOGS_ACTION_CREATED_AT ON AUDIT_LOGS (ACTION, CREATED_AT DESC);
CREATE INDEX IF NOT EXISTS IDX_AUDIT_LOGS_USER_ID ON AUDIT_LOGS (USER_ID);
CREATE UNIQUE INDEX IF NOT EXISTS UQ_ENROLLMENTS_COURSE_STUDENT ON ENROLLMENTS (COURSE_ID, STUDENT_ID);
CREATE INDEX IF NOT EXISTS IDX_DEVICES_USER_DEVICE ON DEVICES (USER_ID, DEVICE_NAME);
CREATE INDEX IF NOT EXISTS IDX_MESSAGES_COURSE_SENT_AT ON MESSAGES (COURSE_ID, SENT_AT DESC);
CREATE INDEX IF NOT EXISTS IDX_MESSAGES_SENDER_ID ON MESSAGES (SENDER_ID);

-- DATA CHO BẢNG ROLES
INSERT INTO ROLES (NAME, DESCRIPTION)
VALUES
('ADMIN', 'Quản trị hệ thống'),
('TEACHER', 'Giảng viên'),
('STUDENT', 'Học sinh');

-- DATA CHO BẢNG PERMISSIONS
INSERT INTO PERMISSIONS (CODE, NAME, DESCRIPTION)
VALUES
-- Hệ thống
('SYSTEM_MANAGE', 'Quản lý hệ thống', 'Cấu hình chính sách, quản lý toàn bộ hệ thống'),
('VIEW_AUDIT_LOG', 'Xem nhật ký hệ thống', 'Xem audit log'),

-- Người dùng
('USER_MANAGE', 'Quản lý người dùng', 'Tạo/Sửa/Xóa/Khóa tài khoản'),
('USER_ASSIGN_ROLE', 'Phân quyền người dùng', 'Gán quyền cho người dùng'),

-- Khóa học
('COURSE_CREATE', 'Tạo khóa học', 'Tạo khóa học mới'),
('COURSE_UPDATE', 'Cập nhật khóa học', 'Sửa thông tin khóa học'),
('COURSE_DELETE', 'Xóa khóa học', 'Đóng hoặc xóa khóa học'),
('COURSE_VIEW', 'Xem khóa học', 'Xem danh sách khóa học'),

-- Duyệt tham gia
('ENROLL_APPROVE', 'Duyệt tham gia khóa học', 'Duyệt hoặc từ chối yêu cầu'),

-- Bài kiểm tra
('EXAM_CREATE', 'Tạo bài kiểm tra', 'Tạo bài thi'),
('EXAM_UPDATE', 'Cập nhật bài kiểm tra', 'Sửa bài thi'),
('EXAM_DELETE', 'Xóa bài kiểm tra', 'Xóa bài thi'),
('EXAM_TAKE', 'Làm bài kiểm tra', 'Thực hiện bài thi'),
('EXAM_GRADE', 'Chấm điểm', 'Chấm bài và nhập điểm'),
('EXAM_MONITOR', 'Giám sát phòng thi', 'Theo dõi thí sinh'),

-- Tài liệu & học online
('MATERIAL_UPLOAD', 'Upload tài liệu', 'Tải tài liệu lên'),
('MATERIAL_DOWNLOAD', 'Tải tài liệu', 'Tải tài liệu về'),
('ONLINE_SESSION_MANAGE', 'Quản lý buổi học online', 'Tạo và chỉnh sửa buổi học'),
('ONLINE_SESSION_JOIN', 'Tham gia buổi học', 'Tham gia lớp học online'),

-- Thiết bị & vi phạm
('DEVICE_MANAGE', 'Quản lý thiết bị', 'Khóa thiết bị vi phạm'),

-- Thông báo & chat
('NOTIFICATION_SEND', 'Gửi thông báo', 'Gửi thông báo hệ thống'),
('CHAT_USE', 'Sử dụng chat', 'Nhắn tin trong khóa học');

-- GÁN QUYỀN CHO ADMIN (Lấy nguyên toàn bộ ID)
INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID)
SELECT 1, ID FROM PERMISSIONS;

-- GÁN QUYỀN CHO TEACHER
INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID)
SELECT 2, ID FROM PERMISSIONS
WHERE CODE IN (
'COURSE_VIEW',
'EXAM_CREATE','EXAM_UPDATE','EXAM_DELETE',
'EXAM_GRADE','EXAM_MONITOR',
'MATERIAL_UPLOAD',
'ONLINE_SESSION_MANAGE',
'CHAT_USE',
'NOTIFICATION_SEND'
);

-- GÁN QUYỀN CHO STUDENT
INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID)
SELECT 3, ID FROM PERMISSIONS
WHERE CODE IN (
'COURSE_VIEW',
'EXAM_TAKE',
'MATERIAL_DOWNLOAD',
'ONLINE_SESSION_JOIN',
'CHAT_USE'
);

-- TẠO ADMIN ACCOUNT
INSERT INTO users (username, password_hash, full_name, email, role_id, status)
VALUES
(
    'admin',
    '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9',
    'Quản trị viên',
    'admin@courseguard.local',
    1, -- role ADMIN
    'ACTIVE'
);

-- TẠO TÀI KHOẢN GIẢNG VIÊN PHỤC VỤ DỮ LIỆU KHÓA HỌC MẪU
INSERT INTO users (username, password_hash, full_name, email, role_id, status)
VALUES
('thnghi', '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', 'Trần Hồng Nghi', 'thnghi@courseguard.local', 2, 'ACTIVE'),
('ttnghia', '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', 'Tô Trọng Nghĩa', 'ttnghia@courseguard.local', 2, 'ACTIVE'),
('ttdung', '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', 'Trần Tuấn Dũng', 'ttdung@courseguard.local', 2, 'ACTIVE'),
('ptduy', '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', 'Phan Thế Duy', 'ptduy@courseguard.local', 2, 'ACTIVE'),
('dmtrung', '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', 'Đoàn Minh Trung', 'dmtrung@courseguard.local', 2, 'ACTIVE'),
('nhquyen', '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', 'Nguyễn Hữu Quyền', 'nhquyen@courseguard.local', 2, 'ACTIVE'),
('dduy', '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', 'Đoàn Duy', 'dduy@courseguard.local', 2, 'ACTIVE'),
('pttlinh', '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', 'Phạm Thị Thuỳ Linh', 'pttlinh@courseguard.local', 2, 'ACTIVE'),
('dtngat', '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', 'Đỗ Thị Ngát', 'dtngat@courseguard.local', 2, 'ACTIVE');

-- DỮ LIỆU KHÓA HỌC THEO TKB ĐÃ CUNG CẤP
INSERT INTO COURSES
    (COURSE_CODE, CLASS_CODE, NAME, CREDITS, DESCRIPTION, TEACHER_ID, INSTRUCTOR_TEXT, SCHEDULE_TEXT, STATUS)
VALUES
('NT106', 'NT106.Q22.ANTT', 'Lập trình mạng căn bản', 2, 'Lập trình mạng căn bản', (SELECT ID FROM USERS WHERE USERNAME = 'thnghi'), 'Trần Hồng Nghi', 'Thứ 5 Tiết 678 Phòng C311', 'ACTIVE'),
('NT106', 'NT106.Q22.ANTT.2', 'Lập trình mạng căn bản (TH - HT1)', 1, 'Lập trình mạng căn bản (TH - HT1)', (SELECT ID FROM USERS WHERE USERNAME = 'ttnghia'), 'Tô Trọng Nghĩa', 'Thứ 5 Tiết 12345 Phòng B4.08', 'ACTIVE'),
('NT208', 'NT208.Q22.ANTT', 'Lập trình ứng dụng web', 2, 'Lập trình ứng dụng web', (SELECT ID FROM USERS WHERE USERNAME = 'ttdung'), 'Trần Tuấn Dũng', 'Thứ 3 Tiết 678 Phòng B6.08', 'ACTIVE'),
('NT208', 'NT208.Q22.ANTT.1', 'Lập trình ứng dụng web (TH - HT1)', 1, 'Lập trình ứng dụng web (TH - HT1)', (SELECT ID FROM USERS WHERE USERNAME = 'ttdung'), 'Trần Tuấn Dũng', 'Thứ 3 Tiết 12345 Phòng B4.06', 'ACTIVE'),
('NT230', 'NT230.Q22.ANTT', 'Cơ chế hoạt động của mã độc', 2, 'Cơ chế hoạt động của mã độc', (SELECT ID FROM USERS WHERE USERNAME = 'ptduy'), 'Phan Thế Duy', 'Thứ 4 Tiết 23 Phòng C306', 'ACTIVE'),
('NT230', 'NT230.Q22.ANTT.2', 'Cơ chế hoạt động của mã độc (TH - HT1)', 1, 'Cơ chế hoạt động của mã độc (TH - HT1)', (SELECT ID FROM USERS WHERE USERNAME = 'dmtrung'), 'Đoàn Minh Trung', 'Thứ 4 Tiết 67890 Phòng B2.02', 'ACTIVE'),
('NT521', 'NT521.Q21.ANTT', 'Lập trình an toàn và khai thác lỗ hổng phần mềm', 3, 'Lập trình an toàn và khai thác lỗ hổng phần mềm', (SELECT ID FROM USERS WHERE USERNAME = 'ptduy'), 'Phan Thế Duy; Nguyễn Hữu Quyền', 'Thứ 2 Tiết 678 Phòng C306', 'ACTIVE'),
('NT521', 'NT521.Q21.ANTT.1', 'Lập trình an toàn và khai thác lỗ hổng phần mềm (TH - HT1)', 1, 'Lập trình an toàn và khai thác lỗ hổng phần mềm (TH - HT1)', (SELECT ID FROM USERS WHERE USERNAME = 'nhquyen'), 'Nguyễn Hữu Quyền', 'Thứ 2 Tiết 12345 Phòng B5.04', 'ACTIVE'),
('SS004', 'SS004.Q210', 'Kỹ năng nghề nghiệp', 2, 'Kỹ năng nghề nghiệp', (SELECT ID FROM USERS WHERE USERNAME = 'dduy'), 'Đoàn Duy', 'Thứ 6 Tiết 678 Phòng B3.14', 'ACTIVE'),
('SS008', 'SS008.Q26', 'Kinh tế chính trị Mác – Lênin', 2, 'Kinh tế chính trị Mác – Lênin', (SELECT ID FROM USERS WHERE USERNAME = 'pttlinh'), 'Phạm Thị Thuỳ Linh', 'Thứ 6 Tiết 45 Phòng B1.14', 'ACTIVE'),
('SS009', 'SS009.Q24', 'Chủ nghĩa xã hội khoa học', 2, 'Chủ nghĩa xã hội khoa học', (SELECT ID FROM USERS WHERE USERNAME = 'dtngat'), 'Đỗ Thị Ngát', 'Thứ 3 Tiết 90 Phòng B4.14', 'ACTIVE');

-- TẠO STUDENT ACCOUNT (cho team test)
INSERT INTO users (username, password_hash, full_name, email, role_id, status)
VALUES
(
    'student',
    '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9',
    'Student Test',
    'student@courseguard.local',
    3, -- role STUDENT
    'ACTIVE'
);

-- =========================================================
-- [END] SupabaseSchema.sql
-- =========================================================

-- =========================================================
-- [BEGIN] Migrations/20260415_security_constraints.sql
-- =========================================================
-- 2026-04-15: data consistency constraints for enrollment/device flows
-- Run once in production with privileged DB account.
BEGIN;

WITH ranked_enrollments AS (
    SELECT id,
           ROW_NUMBER() OVER (PARTITION BY course_id, student_id ORDER BY id) AS rn
    FROM enrollments
)
DELETE FROM enrollments
WHERE id IN (SELECT id FROM ranked_enrollments WHERE rn > 1);

CREATE UNIQUE INDEX IF NOT EXISTS uq_enrollments_course_student
ON enrollments (course_id, student_id);

CREATE INDEX IF NOT EXISTS idx_devices_user_device
ON devices (user_id, device_name);

COMMIT;
-- =========================================================
-- [END] Migrations/20260415_security_constraints.sql
-- =========================================================

-- =========================================================
-- [BEGIN] Migrations/20260415_extend_courses_for_schedule.sql
-- =========================================================
-- Extend COURSES table to store academic timetable metadata.
-- Safe to run multiple times.
ALTER TABLE COURSES ADD COLUMN IF NOT EXISTS COURSE_CODE VARCHAR(20);
ALTER TABLE COURSES ADD COLUMN IF NOT EXISTS CLASS_CODE VARCHAR(50);
ALTER TABLE COURSES ADD COLUMN IF NOT EXISTS CREDITS INT;
ALTER TABLE COURSES ADD COLUMN IF NOT EXISTS INSTRUCTOR_TEXT VARCHAR(255);
ALTER TABLE COURSES ADD COLUMN IF NOT EXISTS SCHEDULE_TEXT VARCHAR(255);
CREATE INDEX IF NOT EXISTS IDX_COURSES_CODE ON COURSES (COURSE_CODE);
CREATE INDEX IF NOT EXISTS IDX_COURSES_CLASS_CODE ON COURSES (CLASS_CODE);
-- =========================================================
-- [END] Migrations/20260415_extend_courses_for_schedule.sql
-- =========================================================

-- =========================================================
-- [BEGIN] Migrations/20260416_normalize_user_status.sql
-- =========================================================
-- 2026-04-16: normalize status values for schema-compatible filtering
-- Run once after deploying latest backend changes.
BEGIN;
UPDATE USERS
SET STATUS = UPPER(COALESCE(STATUS, 'ACTIVE'))
WHERE STATUS IS NULL
   OR STATUS <> UPPER(STATUS);
COMMIT;
-- =========================================================
-- [END] Migrations/20260416_normalize_user_status.sql
-- =========================================================
