-- SUPABASE (POSTGRESQL) SCHEMA INIT SCRIPT
-- Bỏ qua lệnh CREATE DATABASE / USE vì Supabase đã tự xử lý Database mặc định là postgres.

-- ROLES
CREATE TABLE ROLES (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR(255)
);

-- USERS
CREATE TABLE USERS (
    ID SERIAL PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    FULL_NAME VARCHAR(100),
    EMAIL VARCHAR(100) UNIQUE,
    ROLE_ID INT NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_USERS_ROLES 
    FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID)
);

-- PERMISSIONS
CREATE TABLE PERMISSIONS (
    ID SERIAL PRIMARY KEY,
    CODE VARCHAR(100) NOT NULL UNIQUE,
    NAME VARCHAR(100),
    DESCRIPTION VARCHAR(255),
    IS_ACTIVE BOOLEAN DEFAULT TRUE
);

-- ROLE_PERMISSIONS
CREATE TABLE ROLE_PERMISSIONS (
    ROLE_ID INT NOT NULL,
    PERMISSION_ID INT NOT NULL,

    PRIMARY KEY (ROLE_ID, PERMISSION_ID),

    FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID) ON DELETE CASCADE,
    FOREIGN KEY (PERMISSION_ID) REFERENCES PERMISSIONS(ID) ON DELETE CASCADE
);

-- COURSES
CREATE TABLE COURSES (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(200) NOT NULL,
    DESCRIPTION TEXT,
    TEACHER_ID INT NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    START_DATE DATE,
    END_DATE DATE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (TEACHER_ID) REFERENCES USERS(ID)
);

-- ENROLLMENTS
CREATE TABLE ENROLLMENTS (
    ID SERIAL PRIMARY KEY,
    COURSE_ID INT NOT NULL,
    STUDENT_ID INT NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'PENDING',
    JOINED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (COURSE_ID) REFERENCES COURSES(ID) ON DELETE CASCADE,
    FOREIGN KEY (STUDENT_ID) REFERENCES USERS(ID)
);

-- EXAMS
CREATE TABLE EXAMS (
    ID SERIAL PRIMARY KEY,
    COURSE_ID INT NOT NULL,
    TITLE VARCHAR(200),
    OPEN_TIME TIMESTAMP,
    CLOSE_TIME TIMESTAMP,
    DURATION_MINUTES INT,
    MAX_ATTEMPTS INT DEFAULT 1,
    ALLOW_REVIEW BOOLEAN DEFAULT FALSE,
    SHUFFLE_QUESTIONS BOOLEAN DEFAULT FALSE,
    CREATED_BY INT,

    FOREIGN KEY (COURSE_ID) REFERENCES COURSES(ID) ON DELETE CASCADE,
    FOREIGN KEY (CREATED_BY) REFERENCES USERS(ID)
);

-- QUESTIONS
CREATE TABLE QUESTIONS (
    ID SERIAL PRIMARY KEY,
    COURSE_ID INT NOT NULL,
    CONTENT TEXT,
    TYPE VARCHAR(20),
    CORRECT_ANSWER TEXT,
    SCORE DECIMAL(5,2) DEFAULT 1,

    FOREIGN KEY (COURSE_ID) REFERENCES COURSES(ID) ON DELETE CASCADE
);

-- EXAM_QUESTIONS
CREATE TABLE EXAM_QUESTIONS (
    EXAM_ID INT NOT NULL,
    QUESTION_ID INT NOT NULL,

    PRIMARY KEY (EXAM_ID, QUESTION_ID),

    FOREIGN KEY (EXAM_ID) REFERENCES EXAMS(ID) ON DELETE CASCADE,
    FOREIGN KEY (QUESTION_ID) REFERENCES QUESTIONS(ID)
);

-- EXAM_ATTEMPTS
CREATE TABLE EXAM_ATTEMPTS (
    ID SERIAL PRIMARY KEY,
    EXAM_ID INT NOT NULL,
    STUDENT_ID INT NOT NULL,
    START_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    SUBMIT_TIME TIMESTAMP,
    SCORE DECIMAL(5,2),
    STATUS VARCHAR(20) DEFAULT 'IN_PROGRESS',

    FOREIGN KEY (EXAM_ID) REFERENCES EXAMS(ID) ON DELETE CASCADE,
    FOREIGN KEY (STUDENT_ID) REFERENCES USERS(ID)
);

-- ANSWERS
CREATE TABLE ANSWERS (
    ID SERIAL PRIMARY KEY,
    ATTEMPT_ID INT NOT NULL,
    QUESTION_ID INT NOT NULL,
    ANSWER_CONTENT TEXT,
    SCORE DECIMAL(5,2),

    FOREIGN KEY (ATTEMPT_ID) REFERENCES EXAM_ATTEMPTS(ID) ON DELETE CASCADE,
    FOREIGN KEY (QUESTION_ID) REFERENCES QUESTIONS(ID)
);

-- ONLINE_SESSIONS
CREATE TABLE ONLINE_SESSIONS (
    ID SERIAL PRIMARY KEY,
    COURSE_ID INT NOT NULL,
    TITLE VARCHAR(200),
    START_TIME TIMESTAMP,
    END_TIME TIMESTAMP,
    MEETING_LINK VARCHAR(500),
    CREATED_BY INT,

    FOREIGN KEY (COURSE_ID) REFERENCES COURSES(ID) ON DELETE CASCADE,
    FOREIGN KEY (CREATED_BY) REFERENCES USERS(ID)
);

-- MATERIALS
CREATE TABLE MATERIALS (
    ID SERIAL PRIMARY KEY,
    COURSE_ID INT NOT NULL,
    FILE_NAME VARCHAR(255),
    FILE_PATH VARCHAR(500),
    UPLOADED_BY INT,
    UPLOADED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (COURSE_ID) REFERENCES COURSES(ID) ON DELETE CASCADE,
    FOREIGN KEY (UPLOADED_BY) REFERENCES USERS(ID)
);

-- MESSAGES
CREATE TABLE MESSAGES (
    ID SERIAL PRIMARY KEY,
    COURSE_ID INT NOT NULL,
    SENDER_ID INT NOT NULL,
    CONTENT TEXT,
    SENT_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (COURSE_ID) REFERENCES COURSES(ID) ON DELETE CASCADE,
    FOREIGN KEY (SENDER_ID) REFERENCES USERS(ID)
);

-- NOTIFICATIONS
CREATE TABLE NOTIFICATIONS (
    ID SERIAL PRIMARY KEY,
    USER_ID INT NOT NULL,
    TITLE VARCHAR(200),
    CONTENT TEXT,
    IS_READ BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

-- DEVICES
CREATE TABLE DEVICES (
    ID SERIAL PRIMARY KEY,
    USER_ID INT NOT NULL,
    DEVICE_NAME VARCHAR(200),
    IP_ADDRESS VARCHAR(50),
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    LAST_ACTIVE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

-- VIOLATIONS
CREATE TABLE VIOLATIONS (
    ID SERIAL PRIMARY KEY,
    USER_ID INT NOT NULL,
    EXAM_ATTEMPT_ID INT,
    TYPE VARCHAR(100),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    FOREIGN KEY (EXAM_ATTEMPT_ID) REFERENCES EXAM_ATTEMPTS(ID)
);

-- AUDIT_LOGS
CREATE TABLE AUDIT_LOGS (
    ID SERIAL PRIMARY KEY,
    USER_ID INT,
    ACTION VARCHAR(200),
    TARGET_TABLE VARCHAR(100),
    TARGET_ID INT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

-- DATA CHO BẢNG ROLES
INSERT INTO ROLES (NAME, DESCRIPTION)
VALUES
('ADMIN', 'Quản trị hệ thống'),
('TEACHER', 'Giảng viên'),
('STUDENT', 'Học sinh');

-- DATA CHO BẢNG PERMISSIONS
INSERT INTO PERMISSIONS (CODE, NAME, DESCRIPTION)
VALUES
-- Hệ thống
('SYSTEM_MANAGE', 'Quản lý hệ thống', 'Cấu hình chính sách, quản lý toàn bộ hệ thống'),
('VIEW_AUDIT_LOG', 'Xem nhật ký hệ thống', 'Xem audit log'),

-- Người dùng
('USER_MANAGE', 'Quản lý người dùng', 'Tạo/Sửa/Xóa/Khóa tài khoản'),
('USER_ASSIGN_ROLE', 'Phân quyền người dùng', 'Gán quyền cho người dùng'),

-- Khóa học
('COURSE_CREATE', 'Tạo khóa học', 'Tạo khóa học mới'),
('COURSE_UPDATE', 'Cập nhật khóa học', 'Sửa thông tin khóa học'),
('COURSE_DELETE', 'Xóa khóa học', 'Đóng hoặc xóa khóa học'),
('COURSE_VIEW', 'Xem khóa học', 'Xem danh sách khóa học'),

-- Duyệt tham gia
('ENROLL_APPROVE', 'Duyệt tham gia khóa học', 'Duyệt hoặc từ chối yêu cầu'),

-- Bài kiểm tra
('EXAM_CREATE', 'Tạo bài kiểm tra', 'Tạo bài thi'),
('EXAM_UPDATE', 'Cập nhật bài kiểm tra', 'Sửa bài thi'),
('EXAM_DELETE', 'Xóa bài kiểm tra', 'Xóa bài thi'),
('EXAM_TAKE', 'Làm bài kiểm tra', 'Thực hiện bài thi'),
('EXAM_GRADE', 'Chấm điểm', 'Chấm bài và nhập điểm'),
('EXAM_MONITOR', 'Giám sát phòng thi', 'Theo dõi thí sinh'),

-- Tài liệu & học online
('MATERIAL_UPLOAD', 'Upload tài liệu', 'Tải tài liệu lên'),
('MATERIAL_DOWNLOAD', 'Tải tài liệu', 'Tải tài liệu về'),
('ONLINE_SESSION_MANAGE', 'Quản lý buổi học online', 'Tạo và chỉnh sửa buổi học'),
('ONLINE_SESSION_JOIN', 'Tham gia buổi học', 'Tham gia lớp học online'),

-- Thiết bị & vi phạm
('DEVICE_MANAGE', 'Quản lý thiết bị', 'Khóa thiết bị vi phạm'),

-- Thông báo & chat
('NOTIFICATION_SEND', 'Gửi thông báo', 'Gửi thông báo hệ thống'),
('CHAT_USE', 'Sử dụng chat', 'Nhắn tin trong khóa học');

-- GÁN QUYỀN CHO ADMIN (Lấy nguyên toàn bộ ID)
INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID)
SELECT 1, ID FROM PERMISSIONS;

-- GÁN QUYỀN CHO TEACHER
INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID)
SELECT 2, ID FROM PERMISSIONS
WHERE CODE IN (
'COURSE_VIEW',
'EXAM_CREATE','EXAM_UPDATE','EXAM_DELETE',
'EXAM_GRADE','EXAM_MONITOR',
'MATERIAL_UPLOAD',
'ONLINE_SESSION_MANAGE',
'CHAT_USE',
'NOTIFICATION_SEND'
);

-- GÁN QUYỀN CHO STUDENT
INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID)
SELECT 3, ID FROM PERMISSIONS
WHERE CODE IN (
'COURSE_VIEW',
'EXAM_TAKE',
'MATERIAL_DOWNLOAD',
'ONLINE_SESSION_JOIN',
'CHAT_USE'
);

-- TẠO ADMIN ACCOUNT
INSERT INTO users (username, password_hash, full_name, email, role_id, status)
VALUES 
(
    'admin',
    '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9',
    'Quản trị viên',
    'admin@courseguard.local',
    1, -- role ADMIN
    'active'
);
