CREATE DATABASE CourseGuardDB
GO
USE CourseGuardDB
GO

-- ROLE
CREATE TABLE ROLES (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NAME NVARCHAR(50) NOT NULL UNIQUE,
    DESCRIPTION NVARCHAR(255)
);

-- USERS
CREATE TABLE USERS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    USERNAME NVARCHAR(50) NOT NULL UNIQUE,
    PASSWORD_HASH NVARCHAR(255) NOT NULL,
    FULL_NAME NVARCHAR(100),
    EMAIL NVARCHAR(100) UNIQUE,
    ROLE_ID INT NOT NULL,
    STATUS NVARCHAR(20) DEFAULT 'ACTIVE',
    CREATED_AT DATETIME DEFAULT GETDATE(),

    CONSTRAINT FK_USERS_ROLES 
    FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID)
);

-- PERMISSIONS
CREATE TABLE PERMISSIONS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    CODE NVARCHAR(100) NOT NULL UNIQUE,
    NAME NVARCHAR(100),
    DESCRIPTION NVARCHAR(255),
    IS_ACTIVE BIT DEFAULT 1
);

-- ROLE_PERMISSIONS
CREATE TABLE ROLE_PERMISSIONS (
    ROLE_ID INT NOT NULL,
    PERMISSION_ID INT NOT NULL,

    PRIMARY KEY (ROLE_ID, PERMISSION_ID),

    FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID) ON DELETE CASCADE,
    FOREIGN KEY (PERMISSION_ID) REFERENCES PERMISSIONS(ID) ON DELETE CASCADE
);

-- COURSES
CREATE TABLE COURSES (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NAME NVARCHAR(200) NOT NULL,
    DESCRIPTION NVARCHAR(MAX),
    TEACHER_ID INT NOT NULL,
    STATUS NVARCHAR(20) DEFAULT 'ACTIVE',
    START_DATE DATE,
    END_DATE DATE,
    CREATED_AT DATETIME DEFAULT GETDATE(),

    FOREIGN KEY (TEACHER_ID) REFERENCES USERS(ID)
);

-- ENROLLMENTS
CREATE TABLE ENROLLMENTS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    COURSE_ID INT NOT NULL,
    STUDENT_ID INT NOT NULL,
    STATUS NVARCHAR(20) DEFAULT 'PENDING',
    JOINED_AT DATETIME DEFAULT GETDATE(),

    FOREIGN KEY (COURSE_ID) REFERENCES COURSES(ID) ON DELETE CASCADE,
    FOREIGN KEY (STUDENT_ID) REFERENCES USERS(ID)
);

-- EXAMS
CREATE TABLE EXAMS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    COURSE_ID INT NOT NULL,
    TITLE NVARCHAR(200),
    OPEN_TIME DATETIME,
    CLOSE_TIME DATETIME,
    DURATION_MINUTES INT,
    MAX_ATTEMPTS INT DEFAULT 1,
    ALLOW_REVIEW BIT DEFAULT 0,
    SHUFFLE_QUESTIONS BIT DEFAULT 0,
    CREATED_BY INT,

    FOREIGN KEY (COURSE_ID) REFERENCES COURSES(ID) ON DELETE CASCADE,
    FOREIGN KEY (CREATED_BY) REFERENCES USERS(ID)
);

-- QUESTIONS
CREATE TABLE QUESTIONS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    COURSE_ID INT NOT NULL,
    CONTENT NVARCHAR(MAX),
    TYPE NVARCHAR(20),
    CORRECT_ANSWER NVARCHAR(MAX),
    SCORE DECIMAL(5,2) DEFAULT 1,

    FOREIGN KEY (COURSE_ID) REFERENCES COURSES(ID) ON DELETE CASCADE
);

-- EXAM_QUESTIONS
CREATE TABLE EXAM_QUESTIONS (
    EXAM_ID INT NOT NULL,
    QUESTION_ID INT NOT NULL,

    PRIMARY KEY (EXAM_ID, QUESTION_ID),

    FOREIGN KEY (EXAM_ID) REFERENCES EXAMS(ID) ON DELETE CASCADE,
    FOREIGN KEY (QUESTION_ID) REFERENCES QUESTIONS(ID)
);

-- EXAM_ATTEMPTS
CREATE TABLE EXAM_ATTEMPTS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    EXAM_ID INT NOT NULL,
    STUDENT_ID INT NOT NULL,
    START_TIME DATETIME DEFAULT GETDATE(),
    SUBMIT_TIME DATETIME,
    SCORE DECIMAL(5,2),
    STATUS NVARCHAR(20) DEFAULT 'IN_PROGRESS',

    FOREIGN KEY (EXAM_ID) REFERENCES EXAMS(ID) ON DELETE CASCADE,
    FOREIGN KEY (STUDENT_ID) REFERENCES USERS(ID)
);

-- ANSWERS
CREATE TABLE ANSWERS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    ATTEMPT_ID INT NOT NULL,
    QUESTION_ID INT NOT NULL,
    ANSWER_CONTENT NVARCHAR(MAX),
    SCORE DECIMAL(5,2),

    FOREIGN KEY (ATTEMPT_ID) REFERENCES EXAM_ATTEMPTS(ID) ON DELETE CASCADE,
    FOREIGN KEY (QUESTION_ID) REFERENCES QUESTIONS(ID)
);

-- ONLINE_SESSIONS
CREATE TABLE ONLINE_SESSIONS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    COURSE_ID INT NOT NULL,
    TITLE NVARCHAR(200),
    START_TIME DATETIME,
    END_TIME DATETIME,
    MEETING_LINK NVARCHAR(500),
    CREATED_BY INT,

    FOREIGN KEY (COURSE_ID) REFERENCES COURSES(ID) ON DELETE CASCADE,
    FOREIGN KEY (CREATED_BY) REFERENCES USERS(ID)
);

-- MATERIALS
CREATE TABLE MATERIALS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    COURSE_ID INT NOT NULL,
    FILE_NAME NVARCHAR(255),
    FILE_PATH NVARCHAR(500),
    UPLOADED_BY INT,
    UPLOADED_AT DATETIME DEFAULT GETDATE(),

    FOREIGN KEY (COURSE_ID) REFERENCES COURSES(ID) ON DELETE CASCADE,
    FOREIGN KEY (UPLOADED_BY) REFERENCES USERS(ID)
);

-- MESSAGES
CREATE TABLE MESSAGES (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    COURSE_ID INT NOT NULL,
    SENDER_ID INT NOT NULL,
    CONTENT NVARCHAR(MAX),
    SENT_AT DATETIME DEFAULT GETDATE(),

    FOREIGN KEY (COURSE_ID) REFERENCES COURSES(ID) ON DELETE CASCADE,
    FOREIGN KEY (SENDER_ID) REFERENCES USERS(ID)
);

-- NOTIFICATIONS
CREATE TABLE NOTIFICATIONS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    USER_ID INT NOT NULL,
    TITLE NVARCHAR(200),
    CONTENT NVARCHAR(MAX),
    IS_READ BIT DEFAULT 0,
    CREATED_AT DATETIME DEFAULT GETDATE(),

    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

-- DEVICES
CREATE TABLE DEVICES (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    USER_ID INT NOT NULL,
    DEVICE_NAME NVARCHAR(200),
    IP_ADDRESS NVARCHAR(50),
    STATUS NVARCHAR(20) DEFAULT 'ACTIVE',
    LAST_ACTIVE DATETIME DEFAULT GETDATE(),

    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

-- VIOLATIONS
CREATE TABLE VIOLATIONS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    USER_ID INT NOT NULL,
    EXAM_ATTEMPT_ID INT,
    TYPE NVARCHAR(100),
    CREATED_AT DATETIME DEFAULT GETDATE(),

    FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    FOREIGN KEY (EXAM_ATTEMPT_ID) REFERENCES EXAM_ATTEMPTS(ID)
);

-- AUDIT_LOGS
CREATE TABLE AUDIT_LOGS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    USER_ID INT,
    ACTION NVARCHAR(200),
    TARGET_TABLE NVARCHAR(100),
    TARGET_ID INT,
    CREATED_AT DATETIME DEFAULT GETDATE(),

    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);
go
-- Insert Roles
INSERT INTO ROLES (NAME, DESCRIPTION)
VALUES
(N'ADMIN', N'Quản trị hệ thống'),
(N'TEACHER', N'Giảng viên'),
(N'STUDENT', N'Học sinh');
-- insert permission
INSERT INTO PERMISSIONS (CODE, NAME, DESCRIPTION)
VALUES
-- Hệ thống
(N'SYSTEM_MANAGE', N'Quản lý hệ thống', N'Cấu hình chính sách, quản lý toàn bộ hệ thống'),
(N'VIEW_AUDIT_LOG', N'Xem nhật ký hệ thống', N'Xem audit log'),

-- Người dùng
(N'USER_MANAGE', N'Quản lý người dùng', N'Tạo/Sửa/Xóa/Khóa tài khoản'),
(N'USER_ASSIGN_ROLE', N'Phân quyền người dùng', N'Gán quyền cho người dùng'),

-- Khóa học
(N'COURSE_CREATE', N'Tạo khóa học', N'Tạo khóa học mới'),
(N'COURSE_UPDATE', N'Cập nhật khóa học', N'Sửa thông tin khóa học'),
(N'COURSE_DELETE', N'Xóa khóa học', N'Đóng hoặc xóa khóa học'),
(N'COURSE_VIEW', N'Xem khóa học', N'Xem danh sách khóa học'),

-- Duyệt tham gia
(N'ENROLL_APPROVE', N'Duyệt tham gia khóa học', N'Duyệt hoặc từ chối yêu cầu'),

-- Bài kiểm tra
(N'EXAM_CREATE', N'Tạo bài kiểm tra', N'Tạo bài thi'),
(N'EXAM_UPDATE', N'Cập nhật bài kiểm tra', N'Sửa bài thi'),
(N'EXAM_DELETE', N'Xóa bài kiểm tra', N'Xóa bài thi'),
(N'EXAM_TAKE', N'Làm bài kiểm tra', N'Thực hiện bài thi'),
(N'EXAM_GRADE', N'Chấm điểm', N'Chấm bài và nhập điểm'),
(N'EXAM_MONITOR', N'Giám sát phòng thi', N'Theo dõi thí sinh'),

-- Tài liệu & học online
(N'MATERIAL_UPLOAD', N'Upload tài liệu', N'Tải tài liệu lên'),
(N'MATERIAL_DOWNLOAD', N'Tải tài liệu', N'Tải tài liệu về'),
(N'ONLINE_SESSION_MANAGE', N'Quản lý buổi học online', N'Tạo và chỉnh sửa buổi học'),
(N'ONLINE_SESSION_JOIN', N'Tham gia buổi học', N'Tham gia lớp học online'),

-- Thiết bị & vi phạm
(N'DEVICE_MANAGE', N'Quản lý thiết bị', N'Khóa thiết bị vi phạm'),

-- Thông báo & chat
(N'NOTIFICATION_SEND', N'Gửi thông báo', N'Gửi thông báo hệ thống'),
(N'CHAT_USE', N'Sử dụng chat', N'Nhắn tin trong khóa học');

-- Gán permission cho từng role
-- Admin
INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID)
SELECT 1, ID FROM PERMISSIONS;
-- Teacher
INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID)
SELECT 2, ID FROM PERMISSIONS
WHERE CODE IN (
'COURSE_VIEW',
'EXAM_CREATE','EXAM_UPDATE','EXAM_DELETE',
'EXAM_GRADE','EXAM_MONITOR',
'MATERIAL_UPLOAD',
'ONLINE_SESSION_MANAGE',
'CHAT_USE',
'NOTIFICATION_SEND'
);
-- Student
INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID)
SELECT 3, ID FROM PERMISSIONS
WHERE CODE IN (
'COURSE_VIEW',
'EXAM_TAKE',
'MATERIAL_DOWNLOAD',
'ONLINE_SESSION_JOIN',
'CHAT_USE'
);
-- Thêm admin để tạo dashboard admin
INSERT INTO users (username, password_hash, full_name, email, role_id, status, created_at)
VALUES 
(
    'admin',
    '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9',
    N'Quản trị viên',
    'admin@courseguard.local',
    1, -- role ADMIN
    'active',
    GETDATE()
);


